/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlarmRecord {
  'id' : string,
  'repeatDays' : Array<bigint>,
  'name' : string,
  'isEnabled' : boolean,
  'timeHour' : bigint,
  'requireMathProblem' : boolean,
  'timeMinute' : bigint,
}
export interface PinnedZone {
  'id' : string,
  'timezone' : string,
  'cityName' : string,
  'countryCode' : string,
}
export interface TimerPreset {
  'id' : string,
  'name' : string,
  'durationSeconds' : bigint,
  'category' : string,
}
export interface UserSettings { 'use24HourFormat' : boolean }
export interface _SERVICE {
  'addPinnedZone' : ActorMethod<[PinnedZone], undefined>,
  'deleteAlarm' : ActorMethod<[string], undefined>,
  'deleteTimerPreset' : ActorMethod<[string], undefined>,
  'getAlarms' : ActorMethod<[], Array<AlarmRecord>>,
  'getPinnedZones' : ActorMethod<[], Array<PinnedZone>>,
  'getTimerPresets' : ActorMethod<[], Array<TimerPreset>>,
  'getUserSettings' : ActorMethod<[], UserSettings>,
  'removePinnedZone' : ActorMethod<[string], undefined>,
  'saveAlarm' : ActorMethod<[AlarmRecord], undefined>,
  'saveTimerPreset' : ActorMethod<[TimerPreset], undefined>,
  'saveUserSettings' : ActorMethod<[UserSettings], undefined>,
  'toggleAlarm' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];