/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PinnedZone = IDL.Record({
  'id' : IDL.Text,
  'timezone' : IDL.Text,
  'cityName' : IDL.Text,
  'countryCode' : IDL.Text,
});
export const AlarmRecord = IDL.Record({
  'id' : IDL.Text,
  'repeatDays' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'isEnabled' : IDL.Bool,
  'timeHour' : IDL.Nat,
  'requireMathProblem' : IDL.Bool,
  'timeMinute' : IDL.Nat,
});
export const TimerPreset = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'category' : IDL.Text,
});
export const UserSettings = IDL.Record({ 'use24HourFormat' : IDL.Bool });

export const idlService = IDL.Service({
  'addPinnedZone' : IDL.Func([PinnedZone], [], []),
  'deleteAlarm' : IDL.Func([IDL.Text], [], []),
  'deleteTimerPreset' : IDL.Func([IDL.Text], [], []),
  'getAlarms' : IDL.Func([], [IDL.Vec(AlarmRecord)], ['query']),
  'getPinnedZones' : IDL.Func([], [IDL.Vec(PinnedZone)], ['query']),
  'getTimerPresets' : IDL.Func([], [IDL.Vec(TimerPreset)], ['query']),
  'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
  'removePinnedZone' : IDL.Func([IDL.Text], [], []),
  'saveAlarm' : IDL.Func([AlarmRecord], [], []),
  'saveTimerPreset' : IDL.Func([TimerPreset], [], []),
  'saveUserSettings' : IDL.Func([UserSettings], [], []),
  'toggleAlarm' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PinnedZone = IDL.Record({
    'id' : IDL.Text,
    'timezone' : IDL.Text,
    'cityName' : IDL.Text,
    'countryCode' : IDL.Text,
  });
  const AlarmRecord = IDL.Record({
    'id' : IDL.Text,
    'repeatDays' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'isEnabled' : IDL.Bool,
    'timeHour' : IDL.Nat,
    'requireMathProblem' : IDL.Bool,
    'timeMinute' : IDL.Nat,
  });
  const TimerPreset = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'category' : IDL.Text,
  });
  const UserSettings = IDL.Record({ 'use24HourFormat' : IDL.Bool });
  
  return IDL.Service({
    'addPinnedZone' : IDL.Func([PinnedZone], [], []),
    'deleteAlarm' : IDL.Func([IDL.Text], [], []),
    'deleteTimerPreset' : IDL.Func([IDL.Text], [], []),
    'getAlarms' : IDL.Func([], [IDL.Vec(AlarmRecord)], ['query']),
    'getPinnedZones' : IDL.Func([], [IDL.Vec(PinnedZone)], ['query']),
    'getTimerPresets' : IDL.Func([], [IDL.Vec(TimerPreset)], ['query']),
    'getUserSettings' : IDL.Func([], [UserSettings], ['query']),
    'removePinnedZone' : IDL.Func([IDL.Text], [], []),
    'saveAlarm' : IDL.Func([AlarmRecord], [], []),
    'saveTimerPreset' : IDL.Func([TimerPreset], [], []),
    'saveUserSettings' : IDL.Func([UserSettings], [], []),
    'toggleAlarm' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };